apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -n tachidesk -o tachidesk
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: suwayomi
  name: suwayomi
  namespace: tachidesk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: suwayomi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -n tachidesk -o tachidesk
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/tachidesk-default: "true"
        io.kompose.service: suwayomi
    spec:
      containers:
        - env:
            - name: BASIC_AUTH_ENABLED
              value: "true"
            - name: BASIC_AUTH_PASSWORD
              value: hello123
            - name: BASIC_AUTH_USERNAME
              value: manga
            - name: BIND_IP
              value: 0.0.0.0
            - name: BIND_PORT
              value: "4567"
            - name: DEBUG
              value: "true"
            - name: DOWNLOAD_AS_CBZ
              value: "true"
            - name: MAX_PARALLEL_UPDATE
              value: "3"
            - name: SOCKS_PROXY_ENABLED
              value: "false"
            - name: TZ
              value: Etc/UTC
          image: ghcr.io/suwayomi/tachidesk:latest
          name: suwayomi
          ports:
            - containerPort: 4567
              hostPort: 4567
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/suwayomi/.local/share/Tachidesk
              name: suwayomi-claim0
      restartPolicy: Always
      volumes:
        - name: suwayomi-claim0
          persistentVolumeClaim:
            claimName: suwayomi-claim0
status: {}
